### ISSUE TITLE
Enable use of regex in .gradient_ignore

### ISSUE THREAD

**Issue by alanvardy** [esl/gradient#172]
Could we add regexes to `.gradient_ignore.exs` in the same vein as `.dialyzer_ignore.exs`, i.e.

```elixir
[
  ~r|apps/my_buggy_app/.*|
]
```

If you can show me where the code change would be I could take a crack at a PR myself :+1:

**Comment by erszcz** [comment]
Hi, @alanvardy!

That's a great idea! If you could spare the time, then the parts to change would be https://github.com/esl/gradient/blob/2417d6f4d40592a0b827ebcde2399c69aab941b1/lib/gradient/error.ex#L381-L415 where we would have to introduce regex matches in the function body instead of just pattern matching by using the `file` variable in multiple patterns in the function heads.

There might be something to tweak in `parse_applicable_ignores` in the same file, depending on how we want to introduce regexes. In the snippet above you can see there are various _ignore rules_ tagged as `ignore_file`, `ignore_kind`, etc. The simplest approach would be to introduce another one like them: `ignore_regex`. A different approach would be to allow for a regex wherever we currently expect a path, but it would require some more effort.

I'm glad you find Gradient useful!
