### ISSUE TITLE
The pattern %{tag_name: _gen} on line X doesn't have the type acc()

### ISSUE THREAD

**Issue by eksperimental** [esl/gradient#33]
This is my project and commit
https://github.com/eksperimental/beam_langs_meta_data/tree/26ecd958475bedd5c0e4204814e7437484acdff4

> lib/beam_langs_meta_data/util.ex: The pattern %{tag_name: _gen} on line 178 doesn't have the type acc()

I am unable to understand this error and what needs to be fixed.

**Comment by erszcz** [comment]
This is tricky. It seems to stem from the use of the dot access operator. I'm not sure yet what code this access is compiled to, but it seems to be the culprit. The code inserted by the Elixir compiler instead of the operator leads to the warning returned by the type checker.

**Comment by halostatue** [comment]
I’m having a similar issue (`lib/app_identity/versions.ex: The pattern %{generate_nonce: _gen} on line 61 doesn't have the type atom()`) where the line in question is `{:ok, mod} -> mod.generate_nonce()` (the project is https://github.com/KineticCafe/app_identity, in the `elixir/` directory). The line numbers may not match up exactly because I’m starting to toy with gradualizer / gradient.

**Comment by erszcz** [comment]
@halostatue Thanks for the report and for your interest in Gradient!

The warning you're getting is a false positive. It's another instance of the same issue as described in https://github.com/esl/gradient/issues/94. We'll get it fixed shortly.

Thanks again!
