### ISSUE TITLE
mix gradient: ensure that deps are imported correctly to Gradualizer

### ISSUE THREAD

**Issue by erszcz** [esl/gradient#4]

**Comment by Premwoik** [comment]
I found out that we don't need to import files to the `gradualizer_db` manually because it is done in the `gradualizer_db:init` function.
https://github.com/josefs/Gradualizer/blob/ab75f28f9e6f6195c01ddd6a132cd7a07b7e52a2/src/gradualizer_db.erl#L165-L169

So I think I can safely remove the code that imports dependencies in the `Gradient` mix task. What do you think @erszcz?
https://github.com/esl/gradient/blob/370c895927263efb2ecd08ae6ca280ac58351b40/lib/mix/tasks/gradient.ex#L102-L109
